### ISSUE TITLE
Feature: User can browse the catalog for hats

### ISSUE THREAD

**Issue by nimcastano** [nimcastano/Cap-Central#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to browse the catalog for hats
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

They can scroll up and down the home page to see a multitude of hats.
There will also be a carousel to show off certain hats.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1001" alt="Screenshot 2023-06-06 at 1 57 05 PM" src="https://github.com/nimcastano/Cap-Central/assets/126118228/7b7c2f7e-61b0-430b-b03d-45d0edc0514c">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include needed tables
   - [x]  product table with productId, description, etc
   - [x]  user table with userId, username, etc
   - [x]  cart table that uses userId and productId
- [x] Update `data.sql` to include products
   - [x]  browse the web for hats
   - [x] find pictures and descriptions
   - [x] find titles for the hats
   - [x] include all that information to insert into the DB for each product

### ☁️ Server Tasks

- [x] Update `server.js` to get (fetch) all the products from products table
   - [x] ensure to try/catch and handle errors
- [x] use a listen to make sure the connection is good
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render the catalog page
- [x] create a carousel component
- [x] create a navbar component
- [x] components should be routed from App.js
- [x] Update components to be clickable and have access to productId

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
